---
name: Amaptive
shortname: Amaptive
github: sszcanada/Amaptive
url: https://github.com/sszcanada/Amaptive


type: PayPal
url: https://ssz.ca/paypal


description:
The Amaptive project is a collaborative project between OpenAI and SSZ Canada, aimed at advancing the field of robotics and AI, promoting education and innovation in these areas, and providing an open-source platform for researchers and educators to build upon and customize for their own purposes. 

The project is currently in development phase and we are actively seeking funding from individuals, businesses, and corporations who believe in our project and want to support our goals. I am a father of 6 kids, with an extremely limited budget, we are trying to make this project happen with what we have. Every little bit helps and we are extremely grateful for any support we receive.

If you or your business are interested in supporting our project and contributing to our goals, please consider making a donation via any of the funding options provided above. Your support will help us to continue developing this project and bringing it to fruition. Thank you for your consideration!
